import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { RootLayoutProps } from "@/types";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={montserrat.className}>{children}</body>
      </html>
    </>
  );
}
