export const courses = [
  {
    img: "/icons/course/1.png",
    title: "Grafik dizayn + AI 1.0",
    path: "courses/grafik-dizayn",
    desc: "Grafik dizayn: g'oyadan eng shedevrgacha. Ijodkorligingizni biz bilan boshlang!",
    month: 5,
  },
  {
    img: "/icons/course/2.png",
    title: "Interior/Exterior dizayn +AI 1.0",
    path: "courses/interior-exterior-dizayn",
    desc: "Interer dizayni: mukammal makon yaratish san'ati. Professionallik sari sayohatingizni bugun boshlang!",
    month: 3,
  },
  {
    img: "/icons/course/3.png",
    title: "Motion dizayn Videomontaj +AI 1.0",
    path: "courses/moushin-dizayn",
    desc: "Moushen grafika va videomontaj, multimedia dizayni va yaratilishining ikki muhim sohasidir!",
    month: 3,
  },
  {
    img: "/icons/course/4.png",
    title: "No-Coding Web/Mobile 1.0",
    path: "courses/no-coding",
    desc: "Bir qator kodsiz g'oyalarni ilovalarga aylantiring loyihalaringiz kelajagi shu yerdan boshlanadi!",
    month: 6,
  },
  {
    img: "/icons/course/5.png",
    title: "Kompyuter savodxonligi 1.0",
    path: "courses/kompyuter-savodxonligi",
    desc: "Texnologiyani o'zlashtiring, kelajakni o'zlashtiring: kompyuter savodxonligiga yo'lingiz shu yerda boshlanadi!",
    month: 1,
  },
  {
    img: "/icons/course/6.png",
    title: "Bir oyda bir veb-sayt",
    path: "courses/bir-oyda-bir-veb-sayt",
    desc: "Bir qator kodsiz g'oyalarni ilovalarga aylantiring loyihalaringiz kelajagi shu yerdan boshlanadi!",
    month: 1,
  },
  {
    img: "/icons/course/4.png",
    title: "Coding foundation + AI 1.0",
    path: "courses/foundation",
    desc: "Dasturlash san'atini o'zlashtirish uchun birinchi qadam bizdan boshlanadi!",
    month: 1,
  },
  {
    img: "/icons/course/7.png",
    title: "Frontend React JS + AI 1.0",
    path: "courses/frontend-reactjs",
    desc: "React.js dinamik va intuitiv veb-ilovalarni yaratish kalitidir!",
    month: 6,
  },
  {
    img: "/icons/course/8.png",
    title: "Python-Django-TensorFlow +AI 1.0",
    path: "courses/python",
    desc: "G'oyalarni haqiqatga aylantirish: Python va Django sizning professional rivojlanishga ilk qadamingiz!",
    month: 6,
  },
];
